const express = require('express')
const activityController = require('../controllers/activityController')
const router = express.Router()

router.route('/student')
.post(activityController.createStudent)
.get(activityController.getStudents)
router.get('/student/:id', activityController.getStudent)
router.route('/supervisor')
.post(activityController.createSupervisor)
router.post('/configactivity', activityController.configActivity)
router.get('/activity/:id', activityController.getActivity)
router.get('/activities', activityController.getActivities)
router.post('/analyticactivity', activityController.submitanalytic)
router.get('/getAnalytics', activityController.getAnalytics)
router.post('/submitwork', activityController.submitWorkActivity)
router.get('/getworks', activityController.getWorks)
router.post('/submitcomment', activityController.comment)
router.get('/getcomment/:id', activityController.getComment)
module.exports = router